dist: bionic
language: python
python:
- '3.7'
- '3.7-dev'
- '3.8-dev'
before_install: pip install 'pip ~= 19.2.3'
install: pip install 'tox-travis ~= 0.12.0'
script: tox
deploy:
  provider: pypi
  user: __token__
  password:
    secure: DIqGPgBeKKfLVRDJTGqKGmnXrhRSTX98z577OCO0EBJwxgyHt32dnuJ9lCVcjlrxcuAs2J78bfBtwieozLRvQR6tbu3M9AU0YTX5pFe9m1kJ7sc8YVpktvXvLslVq27QY2ZuAOoRIi+dU2MlFtsgTgith47X/DXg8333D7XVbUt5Gz7AHecROU/BjheJOEDVPK6SjH+3tpyA+dD1NvLdYHI/jwimtCmQCqWCXZi2/3jlYiLi0tmecqzj7qPFioNGUlGxEyoHehH8f25rtMi6AJ87sCGOi1f89qjXC+leanF1MZHcKTzfY/chh9WzsxTpvQ/vC4YZ3s4XBDzBF6izygJfBnP4RZpWCajgeeXvjx2DBq4sDwHlg8VwK2Dc1OKsQzl2wOFFRFJQ1DNomy/zb6ypTG2EBNgKp/azczHRiYsFkLQCruO6wEmFlBCEQgHnmxEwW92W5PYmhmBTSGMjcfhyP3NFUnh5sMq8DOH6+xjKNjaHV3iwVCv3nmgdZCaISQWlPmILaRC91yKdZoNmhulU5QjK4yb1HoH5r2waZpIq6zPrTFHfxyV1fiDk74wZFIDESWQV0Z+vP/Ogop2WXsJWYy+VUyffMV2LfpksEWFQhJ2OEQslmy/74GDitoV+wC8N7CFz6prf4orF2AQX+kZuZFh8/1DK0ky/eGMyZCw=
  distributions: sdist bdist_wheel
  on:
    repo: dmtucker/verdoc
    branch: master
    tags: true
    python: '3.7'
  skip_existing: true
